### ISSUE TITLE
EDMC plugin

### ISSUE THREAD

**Issue by thargosu** [elitedangereuse/ShipInteriors#14]

**Comment by aussig** [comment]
Hi @thargosu I see you have plans for an EDMC plugin. I have some experience writing plugins for EDMC ([BGS-Tally](https://github.com/aussig/BGS-Tally)), so am happy to help if you need it?

**Comment by thargosu** [comment]
Yes! That would be awesome. I need to bootstrap basically. My intent is to send ship data (status of the ship, cargo, etc) to a websocket server.

**Comment by aussig** [comment]
Want me to throw a framework together that we can flesh out? - I can include automatic plugin updating (version detection from GitHub) as I implemented that for BGST.

If so, do you have a repo set up already?

**Comment by thargosu** [comment]
Thanks again for your precious help!
